### ISSUE TITLE
Migrating settings to 0.2.0 structure fails (from 0.1.27 structure)

### ISSUE THREAD

**Issue by Corvo** [fpalsson/com.fp.advanced-scheduler#10]
Using the below settings structure (working in version `0.1.27`) in the new `0.2.0` version fails migration/conversion.

To add some basic info about my two schedules, one is meant for my kitchen rollershutter and the other for my livingroom rollershutter.
Both contain the tag `Actie` and `Trigger`. The `Actie` tag contains the action to perform (open, close, etc.). I have 4 possible actions and using (Homey) logic flow cards I can filter on tag, as such I have 4 flows for each rollershutter.
The `Trigger` tag merely contains my own text representation of what event has occurred. I use the `Trigger` and `Actie` tags both in a "debug" flow which logs the contents to the Homey timeline.

So, without furher ado, my `0.1.27` RAW (json) settings look as follows:

```{"settings":{"schedules":[{"id":1,"name":"Keuken rolluik","active":true,"tokens":[{"id":2,"name":"Actie","type":"string"},{"id":3,"name":"Trigger","type":"string"}],"scheduleitems":[{"id":1,"daystype":"daysofweek","daysarg":127,"timetype":"solar:sunset","timearg":"00:00","tokensetters":[{"id":2,"value":"Dicht"},{"id":3,"value":"Zonsondergang einde"}]},{"id":2,"daystype":"daysofweek","daysarg":127,"timetype":"solar:goldenHourEveningStart","timearg":"00:00","tokensetters":[{"id":2,"value":"Voorkeur"},{"id":3,"value":"Avond gouden uur begin"}]},{"id":3,"daystype":"daysofweek","daysarg":127,"timetype":"solar:sunriseEnd","timearg":"00:00","tokensetters":[{"id":2,"value":"Voorkeur"},{"id":3,"value":"Zonsopgang einde"}]},{"id":4,"daystype":"daysofweek","daysarg":127,"timetype":"solar:goldenHourMorningEnd","timearg":"00:00","tokensetters":[{"id":2,"value":"Bepalen"},{"id":3,"value":"Ochtend gouden uur einde"}]},{"id":5,"daystype":"daysofweek","daysarg":127,"timetype":"solar:solarNoon","timearg":"-01:00","tokensetters":[{"id":2,"value":"Bepalen"},{"id":3,"value":"Hoogste zonnestand -60"}]},{"id":6,"daystype":"daysofweek","daysarg":127,"timetype":"solar:solarNoon","timearg":"01:00","tokensetters":[{"id":2,"value":"Bepalen"},{"id":3,"value":"Hoogste zonnestand +60"}]},{"id":7,"daystype":"daysofweek","daysarg":127,"timetype":"timeofday","timearg":"11:55","tokensetters":[{"id":2,"value":"Bepalen"},{"id":3,"value":"11:55"}]}]},{"id":2,"name":"Woonkamer rolluik","active":true,"tokens":[{"id":1,"name":"Actie","type":"string"},{"id":4,"name":"Trigger","type":"string"}],"scheduleitems":[{"id":1,"daystype":"daysofweek","daysarg":127,"timetype":"solar:sunsetStart","timearg":"00:05","tokensetters":[{"id":1,"value":"Dicht"},{"id":4,"value":"Zonsondergang begin +5"}]},{"id":2,"daystype":"daysofweek","daysarg":127,"timetype":"solar:goldenHourMorningEnd","timearg":"00:01","tokensetters":[{"id":1,"value":"Open"},{"id":4,"value":"Ochtend gouden uur einde +1"}]},{"id":8,"daystype":"daysofweek","daysarg":127,"timetype":"solar:solarNoon","timearg":"02:00","tokensetters":[{"id":1,"value":"Bepalen"},{"id":4,"value":"Hoogste zonnestand +120"}]},{"id":9,"daystype":"daysofweek","daysarg":127,"timetype":"solar:solarNoon","timearg":"-02:00","tokensetters":[{"id":1,"value":"Bepalen"},{"id":4,"value":"Hoogste zonnestand -120"}]}]}]}}```

**Comment by fpalsson** [comment]
Corrected in this commit: https://github.com/fpalsson/com.fp.advanced-scheduler/commit/699cbb4340f5b2f27868f609823cecfe6e8230de
