### ISSUE TITLE
Flow card not registered - Unknown error

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [fpalsson/com.fp.advanced-scheduler#18]
I have installed Adcanced Scheduler 0.3.1 on Homey 7.2.1 and created a schema

Raw settings
`{"settingsVersion":2,"settings":{"schedules":[{"id":1,"name":"Voordeur_licht","active":true,"tokens":[{"id":1,"name":"ZetAan","type":"boolean"}],"scheduleItems":[{"id":1,"daysType":"daysOfWeek","daysArg":127,"mainTrigger":{"timeType":"timeOfDay","time":"06:00"},"tokenSetters":[{"id":1,"value":true}]},{"id":2,"daysType":"daysOfWeek","daysArg":127,"mainTrigger":{"timeType":"solar","sunEvent":"sunriseEnd","solarOffset":"00:00"},"tokenSetters":[{"id":1,"value":false}]},{"id":3,"daysType":"daysOfWeek","daysArg":127,"mainTrigger":{"timeType":"solar","sunEvent":"sunsetStart","solarOffset":"00:00"},"tokenSetters":[{"id":1,"value":true}]},{"id":4,"daysType":"daysOfWeek","daysArg":127,"mainTrigger":{"timeType":"timeOfDay","time":"23:00"},"tokenSetters":[{"id":1,"value":false}]}]}]}}`

Then I try to create a flow: and get the following error:  Unknown error: Flowcard is not registered.

<img width="790" alt="image" src="https://user-images.githubusercontent.com/28575285/152680069-62ed2f7b-8e72-4ddc-8e30-f42e14ba68a8.png">

To be sure I removed this app from my Homey and reinstalled it.

**Comment by fpalsson** [comment]
I think I have solved the problem. Please test a new version in test: https://homey.app/sv-se/app/com.fp.advanced-scheduler/Advanced-Scheduler/test/

Please let me know if it works as expected!

**Comment by MP-ICT-Diensten** [comment]
This is working now, I can select the schedule from the flow card and no error.

**Comment by fpalsson** [comment]
Thanks for replying. I will close this and push this version live.
