### ISSUE TITLE
Schedule started the flow although the schedule was disabled

### ISSUE THREAD

**Issue by dirkg173** [fpalsson/com.fp.advanced-scheduler#2]
Hi Frederik,
This morning, a test flow was started even though I had disabled the schedule in the app settings. I can reproduce the error.

I have sent you a diagnostic report: ff7981d6-abc3-468a-a456-793b85fd7076
Homey FW: v5.0.0 and v5.0.1-rc1
App version: v0.1.7

![IMG_1773](https://user-images.githubusercontent.com/40319629/110088339-07d60e00-7d95-11eb-9064-7a9cff91db17.PNG)
![IMG_1774](https://user-images.githubusercontent.com/40319629/110088374-13c1d000-7d95-11eb-8082-40ab7195a669.PNG)
<img width="248" alt="Bildschirmfoto 2021-03-05 um 09 26 59" src="https://user-images.githubusercontent.com/40319629/110088397-1c1a0b00-7d95-11eb-9e5c-afffe8d6e5e9.png">

**Comment by fpalsson** [comment]
Thanks for reporting! Bug was found and is corrected in version 0.1.9. It can be installed from https://homey.app/sv-se/app/com.fp.advanced-scheduler/Advanced-Scheduler/test/

Please report if this solves the problem.

**Comment by dirkg173** [comment]
Thanks, I will inform you.

**Comment by dirkg173** [comment]
It's solved! 👍🏼
